[sqlite3]
# go test in the admindb/sqlite package will create this
dbname = "testrun/TestSimple/roomdb"
blacklist = ["gorp_migrations"]


# marshal pub_key strings ala @asdjjasd as feed references.
[[types]]
  [types.match]
    type = "string"
    #tables = ['fallback_auth']
    name = "pub_key"
    nullable = false

  [types.replace]
    type = "roomdb.DBFeedRef"

  [types.imports]
    third_party = ['"github.com/ssb-ngi-pointer/go-ssb-room/roomdb"']